### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by NightHawkSeven** [Lawxsz/Py-obfuscator#1]
Hello there.

I get this error when running the script:

Traceback (most recent call last):
  File "C:\Skynet\obf.py", line 104, in <module>
    lawxszcrykt(code, args.path)
  File "C:\Skynet\obf.py", line 29, in __init__
    self.marshal()
  File "C:\Skynet\obf.py", line 49, in marshal
    self.code = dumps(compile(self.code, "<string>", "exec"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 65
    response.raise_for_status()
IndentationError: unexpected indent

I have added all my imports to the script as well

I use this version of Python:

Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by Lawxsz** [comment]
use 3.10.6

**Comment by NightHawkSeven** [comment]
Thanks, 3.10.6 Solved it. :-)
